### ISSUE TITLE
v1 Todo

### ISSUE THREAD

**Issue by jmeas** [jmeas/resourceful-redux#2]
This lists everything I need to do before the v1 release is ready.

#### Documentation

- [x] Fix the README.md in this directory
- [x] ~~Update the README with some introductory information about the project~~
- [x] Fix CHANGELOG docs
- [x] Host doc site on gh-pages ([this script](https://github.com/reactjs/redux/blob/bf3a557a4ab93ebfc3f9648e88941bb734471c80/package.json#L35) may help)
- [x] Get .js.org domain (https://github.com/js-org/dns.js.org/pull/1290)
- [x] API
  - [x] Example code for `setMeta`
  - [x] Example code for `upsertResources`
- [x] Basic guides
  - [x] Show how to write an action creator
  - [x] Labels
  - [x] Built-in actions
  - [x] Plugins
- [ ] Examples
  - [x] Show how to use the built-in meta to do things
  - [ ] Modal form (saving it, closes modal)
  - [ ] Form with validation maybe?
  - [ ] Bootstrapping page data

#### Source code

- [x] Update the source to match the latest API guides
- [x] Add in single-resource behavior for the bulk action types, now that they're the only ones that there are
- [x] Add request label support for all reducers
- [x] Split out `replace`

#### Releasing/testing

- [x] Hook up Travis/add badge
- [x] Hook up Code Climate
  - [ ] add code coverage badge
- [x] Add more tests
- [x] Release a new version
- [x] Migrate one app over to the new version

**Comment by jmeas** [comment]
Gonna close. The first >0 major version is ready for release imo.
